// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otymbggoovmxtiesnzzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90eW1iZ2dvb3ZteHRpZXNuenpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMjYyMTIsImV4cCI6MjA1NTgwMjIxMn0.j15bPLh7aEPsofPL5ImykTQ6tvs2B6bpDgKj0XTyJ9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);